name: observable_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  connectivity_plus: ^2.3.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^2.4.1
  http: ^1.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.2
  stacked: ^3.4.1+1
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

